/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorProjectIdRouteImport } from './routes/editor.$projectId'
import { Route as ApiPublicRenderUploadRouteImport } from './routes/api/public/render-upload'
import { Route as ApiPublicRenderDownloadRouteImport } from './routes/api/public/render-download'
import { Route as ApiPublicElevenlabsKeyRouteImport } from './routes/api/public/elevenlabs-key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorProjectIdRoute = EditorProjectIdRouteImport.update({
  id: '/editor/$projectId',
  path: '/editor/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRenderUploadRoute = ApiPublicRenderUploadRouteImport.update({
  id: '/api/public/render-upload',
  path: '/api/public/render-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRenderDownloadRoute = ApiPublicRenderDownloadRouteImport.update({
  id: '/api/public/render-download',
  path: '/api/public/render-download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicElevenlabsKeyRoute = ApiPublicElevenlabsKeyRouteImport.update({
  id: '/api/public/elevenlabs-key',
  path: '/api/public/elevenlabs-key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
  '/api/public/elevenlabs-key': typeof ApiPublicElevenlabsKeyRoute
  '/api/public/render-download': typeof ApiPublicRenderDownloadRoute
  '/api/public/render-upload': typeof ApiPublicRenderUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
  '/api/public/elevenlabs-key': typeof ApiPublicElevenlabsKeyRoute
  '/api/public/render-download': typeof ApiPublicRenderDownloadRoute
  '/api/public/render-upload': typeof ApiPublicRenderUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
  '/api/public/elevenlabs-key': typeof ApiPublicElevenlabsKeyRoute
  '/api/public/render-download': typeof ApiPublicRenderDownloadRoute
  '/api/public/render-upload': typeof ApiPublicRenderUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/editor/$projectId'
    | '/api/public/elevenlabs-key'
    | '/api/public/render-download'
    | '/api/public/render-upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/editor/$projectId'
    | '/api/public/elevenlabs-key'
    | '/api/public/render-download'
    | '/api/public/render-upload'
  id:
    | '__root__'
    | '/'
    | '/editor/$projectId'
    | '/api/public/elevenlabs-key'
    | '/api/public/render-download'
    | '/api/public/render-upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorProjectIdRoute: typeof EditorProjectIdRoute
  ApiPublicElevenlabsKeyRoute: typeof ApiPublicElevenlabsKeyRoute
  ApiPublicRenderDownloadRoute: typeof ApiPublicRenderDownloadRoute
  ApiPublicRenderUploadRoute: typeof ApiPublicRenderUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$projectId': {
      id: '/editor/$projectId'
      path: '/editor/$projectId'
      fullPath: '/editor/$projectId'
      preLoaderRoute: typeof EditorProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/render-upload': {
      id: '/api/public/render-upload'
      path: '/api/public/render-upload'
      fullPath: '/api/public/render-upload'
      preLoaderRoute: typeof ApiPublicRenderUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/render-download': {
      id: '/api/public/render-download'
      path: '/api/public/render-download'
      fullPath: '/api/public/render-download'
      preLoaderRoute: typeof ApiPublicRenderDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elevenlabs-key': {
      id: '/api/public/elevenlabs-key'
      path: '/api/public/elevenlabs-key'
      fullPath: '/api/public/elevenlabs-key'
      preLoaderRoute: typeof ApiPublicElevenlabsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorProjectIdRoute: EditorProjectIdRoute,
  ApiPublicElevenlabsKeyRoute: ApiPublicElevenlabsKeyRoute,
  ApiPublicRenderDownloadRoute: ApiPublicRenderDownloadRoute,
  ApiPublicRenderUploadRoute: ApiPublicRenderUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
